### ISSUE TITLE
Display differences within a file

### ISSUE THREAD

**Issue by namdien177** [namdien177/gitme-git-client#11]
### **Task**

Able to see differences from last commitment of a file

### **Expecting behavior**

- [ ]  View difference within a file
- [ ]  Able to copy context
- [ ]  Show the file in explorer
- [ ]  View stats of diff

### **Piority**

HIGH

### **Additional Note**

- [ ]  Adding search of changes within a file
- [ ]  Highlight difference
- [ ]  Live editing
- [ ]  Open with editor
