### ISSUE TITLE
Complete branching menu

### ISSUE THREAD

**Issue by namdien177** [namdien177/gitme-git-client#17]
### **Task**

Able to see differences from last commitment of a file

### **Expecting behavior**

- [x]  Fixing UI
- [x]  View multiple branches
- [x]  Able checkout
- [x]  Able to create new branch
- [x]  Prevent checkout if has changes
- [x]  Merge and resolve conflict

### **Piority**

HIGH

### **Additional Note**

- [x]  Adding option to stash changes

  <s>Able to stash changes</s> (Not enough time)

- [x]  Add timestamp each fetch/changes
- [ ]  Add statistics summary
- [x]  Delete branch
- [x]  Rename branch

Also reference to #11 : Open file with editor

**Comment by namdien177** [comment]
Graduated. Gonna comeback this one day...
