### ISSUE TITLE
Fix UI clone repository

### ISSUE THREAD

**Issue by namdien177** [namdien177/gitme-git-client#23]
### **Task**

Fixing broken UI

### **Expecting behavior**

- [x] Fix UI
- [x] Check functionality

### **Piority**

HIGH

### **Additional Note**

- [x]  ~~Check SSH~~ (Not enought time)
- [x] Check authentication by OAuth

**Comment by namdien177** [comment]
- [ ] Add loading indicator
- [ ] check load-cycle of the program after cloned/imported
