### ISSUE TITLE
Adding existing repository

### ISSUE THREAD

**Issue by namdien177** [namdien177/gitme-git-client#8]
### **Task**

Adding existing local repository to application control.

### **Expecting behavior**

- [ ]  Distinguish if it's an already-repository
- [ ]  Be able to initialize Git in non-repository local source code
- [ ]  Add information of repository to application manage file
- [ ]  Add associated credentials
- [ ]  Perform fetch/pull

### **Piority**

HIGH

### **Additional Note**

none
