### ISSUE TITLE
Commit file changes

### ISSUE THREAD

**Issue by namdien177** [namdien177/gitme-git-client#9]
### **Task**

Able to commit changes, both all and selected

### **Expecting behavior**

- [x]  Select single/multi/all file to commit
- [x]  Be able to commit

### **Piority**

HIGH

### **Additional Note**

- [x]  Adding notation to identify type of changes
- [x]  Undo changes for single/multiple/all files
- [x]  Able to navigate to directory
- [x]  Add option in each commit and save that option

**Comment by namdien177** [comment]
> ### **Task**
> Able to commit changes, both all and selected
> 
> ### **Expecting behavior**
> * [x]   Select single/multi/all file to commit
> * [x]   Be able to commit
> 
> ### **Piority**
> HIGH
> 
> ### **Additional Note**
> * [x]   Adding notation to identify type of changes
> * [ ]   Undo changes for single/multiple/all files
> * [ ]   Able to navigate to directory
> * [x]   Add option in each commit and save that option
